import type { Metadata } from 'next';
import { DM_Serif_Display, Outfit, Solitreo } from 'next/font/google';
import './globals.css';

const outfit = Outfit({
	variable: '--font-outfit',
	subsets: ['latin'],
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
	display: 'swap',
});

const dmSerfitDisplay = DM_Serif_Display({
	variable: '--font-dm-serif-display',
	subsets: ['latin'],
	weight: ['400'],
	display: 'swap',
});

const solitreo = Solitreo({
	variable: '--font-solitreo',
	subsets: ['latin'],
	weight: ['400'],
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<link rel="preload" as="image" href="/home/hero-video.png" />
			<body
				className={` ${outfit.variable} antialiased relative ${dmSerfitDisplay.variable} ${solitreo.variable} font-outfit `}
			>
				{children}
			</body>
		</html>
	);
}
